services:
  - type: web
    name: instagram-story-downloader-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python a/InstagramStoryDownloader/bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${{ TELEGRAM_TOKEN }}
    regions:
      - oregon
    autoDeploy: true
    healthCheckPath: "/"
    env:
      - key: PYTHON_VERSION
        value: "3.11"
